#!/usr/bin/env bash

# Copyright 2018 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$DIR/package-image.sh -a -b mt8167s_ref -B build-arm64 \
    -d $DIR/../kernel/target/arm64/dtb/dummy-device-tree.dtb -D append \
    -g -m -M 0x40000000

$DIR/flash-avb -b mt8167s_ref
